sonar.projectKey=mrafiasyifaa_revoshop-milestone-3
sonar.organization=mrafiasyifaa
sonar.sources=src
sonar.exclusions=**/__test__/**,**/node_modules/**,**/.next/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
